## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('shutoushu', ['internet', 'wifi'])
    module.includes = '.'
    module.source = [
        'model/shutoushu-packet.cc',
        'model/shutoushu-routing-protocol.cc',
        'helper/shutoushu-helper.cc',
        ]

    #shutoushu_test = bld.create_ns3_module_test_library('shutoushu')
   # shutoushu_test.source = [
      #  'test/shutoushu-id-cache-test-suite.cc',
       # 'test/shutoushu-test-suite.cc',
       # 'test/shutoushu-regression.cc',
       # 'test/bug-772.cc',
       # 'test/loopback.cc',
       # ]

    headers = bld(features='ns3header')
    headers.module = 'shutoushu'
    headers.source = [
        'model/shutoushu-packet.h',
        'model/shutoushu-routing-protocol.h',
        'helper/shutoushu-helper.h',
        ]

    #if bld.env['ENABLE_EXAMPLES']:
     #   bld.recurse('examples')

   # bld.ns3_python_bindings()
